import { AppSidebar } from "@/components/sidebar-components/app-sidebar";
import HeaderSidebar from "@/components/sidebar-components/header-sidebar";

import { Toaster } from "sonner";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";

import React from "react";

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
  icons: {
    icon: [
      { rel: "icon", url: "/favicon.ico" },
      {
        rel: "icon",
        url: "/logo.jpg",
        type: "image/png",
        sizes: "192x192",
      },
      {
        rel: "icon",
        url: "/logo.jpg",
        type: "image/png",
        sizes: "512x512",
      },
    ],
    apple: [{ url: "/logo.jpg", sizes: "180x180", type: "image/png" }],
  },
};

const DashboardLayout = ({ children }) => {
  return (
    <SidebarProvider>
      <Toaster />
      <AppSidebar />
      <SidebarInset>
        <HeaderSidebar />
        <div className="p-4">{children}</div>
      </SidebarInset>
    </SidebarProvider>
  );
};

export default DashboardLayout;
