import "./globals.css";

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Dashboard",
	description: "Generated by create next app",
	icons: {
		icon: [
			{ rel: "icon", url: "/favicon.ico" },
			{
				rel: "icon",
				url: "/logo.jpg",
				type: "image/png",
				sizes: "192x192",
			},
			{
				rel: "icon",
				url: "/logo.jpg",
				type: "image/png",
				sizes: "512x512",
			},
		],
		apple: [{ url: "/logo.jpg", sizes: "180x180", type: "image/png" }],
	},
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${inter.className} antialiased`}>{children}</body>
		</html>
	);
}

